name: tv_shows
description: A Flutter app for TV shows
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.13.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  dio: ^4.0.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.0
  flutter_form_builder: ^6.2.0
  get_it: ^7.2.0
  provider: ^6.0.1
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^0.1.0
  very_good_analysis: ^2.3.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
