// Mocks generated by Mockito 5.0.16 from annotations
// in tv_shows/test/business_logic/viewmodels/shows/shows_viemodel_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_shows/business_logic/models/show.dart' as _i5;
import 'package:tv_shows/business_logic/models/show_details.dart' as _i2;
import 'package:tv_shows/services/shows/shows_service.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeShowDetails_0 extends _i1.Fake implements _i2.ShowDetails {}

/// A class which mocks [ShowsService].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowsService extends _i1.Mock implements _i3.ShowsService {
  MockShowsService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<List<_i5.Show>> getShows() =>
      (super.noSuchMethod(Invocation.method(#getShows, []),
              returnValue: Future<List<_i5.Show>>.value(<_i5.Show>[]))
          as _i4.Future<List<_i5.Show>>);
  @override
  _i4.Future<_i2.ShowDetails> getShowDetails(String? id) =>
      (super.noSuchMethod(Invocation.method(#getShowDetails, [id]),
              returnValue: Future<_i2.ShowDetails>.value(_FakeShowDetails_0()))
          as _i4.Future<_i2.ShowDetails>);
  @override
  String toString() => super.toString();
}
