// Mocks generated by Mockito 5.0.16 from annotations
// in tv_shows/test/services/shows/shows_service_impl_test.dart.
// Do not manually edit this file.

import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_shows/business_logic/utils/episode_utils.dart' as _i3;
import 'package:tv_shows/business_logic/utils/shows_utils.dart' as _i2;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

/// A class which mocks [ShowDetailsRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockShowDetailsRequest extends _i1.Mock
    implements _i2.ShowDetailsRequest {
  MockShowDetailsRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get id =>
      (super.noSuchMethod(Invocation.getter(#id), returnValue: '') as String);
  @override
  String get endpoint =>
      (super.noSuchMethod(Invocation.getter(#endpoint), returnValue: '')
          as String);
  @override
  String toString() => super.toString();
}

/// A class which mocks [AllEpisodesRequest].
///
/// See the documentation for Mockito's code generation for more information.
class MockAllEpisodesRequest extends _i1.Mock
    implements _i3.AllEpisodesRequest {
  MockAllEpisodesRequest() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get showId =>
      (super.noSuchMethod(Invocation.getter(#showId), returnValue: '')
          as String);
  @override
  String get endpoint =>
      (super.noSuchMethod(Invocation.getter(#endpoint), returnValue: '')
          as String);
  @override
  String toString() => super.toString();
}
