// Mocks generated by Mockito 5.0.16 from annotations
// in tv_shows/test/services/episode/episodes_service_impl_test.dart.
// Do not manually edit this file.

import 'dart:async' as _i4;

import 'package:dio/dio.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:tv_shows/business_logic/utils/media_utils.dart' as _i6;
import 'package:tv_shows/services/http/http_service.dart' as _i5;
import 'package:tv_shows/services/image_picker/image_picker.dart' as _i3;

// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types

class _FakeFormData_0 extends _i1.Fake implements _i2.FormData {}

/// A class which mocks [ImagePickerService].
///
/// See the documentation for Mockito's code generation for more information.
class MockImagePickerService extends _i1.Mock
    implements _i3.ImagePickerService {
  MockImagePickerService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.FormData> getFormDataFromImage() =>
      (super.noSuchMethod(Invocation.method(#getFormDataFromImage, []),
              returnValue: Future<_i2.FormData>.value(_FakeFormData_0()))
          as _i4.Future<_i2.FormData>);
  @override
  String toString() => super.toString();
}

/// A class which mocks [BaseHttpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockBaseHttpService extends _i1.Mock implements _i5.BaseHttpService {
  MockBaseHttpService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<dynamic> get({_i5.BaseHttpGetRequest? request}) =>
      (super.noSuchMethod(Invocation.method(#get, [], {#request: request}),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<dynamic> post({_i5.BaseHttpPostRequest? request}) =>
      (super.noSuchMethod(Invocation.method(#post, [], {#request: request}),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<dynamic> delete({_i5.BaseHttpDeleteRequest? request}) =>
      (super.noSuchMethod(Invocation.method(#delete, [], {#request: request}),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  _i4.Future<dynamic> postFormData({_i6.MediaRequest? request}) => (super
      .noSuchMethod(Invocation.method(#postFormData, [], {#request: request}),
          returnValue: Future<dynamic>.value()) as _i4.Future<dynamic>);
  @override
  String toString() => super.toString();
}
